
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class AnaSayfa extends javax.swing.JFrame {

    /**
     * Creates new form AnaSayfa
     */
    public AnaSayfa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        combopersonel = new javax.swing.JComboBox<>();
        txb_ad = new javax.swing.JTextField();
        btn_giris = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_cikis = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txb_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        combopersonel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "OGRETMEN", "OGRENCI", " " }));
        combopersonel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combopersonelActionPerformed(evt);
            }
        });

        btn_giris.setText("GİRİŞ");
        btn_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisActionPerformed(evt);
            }
        });

        jLabel1.setText("AD:");

        jLabel2.setText("ŞİFRE:");

        jLabel3.setText("GİRİŞİ SEÇİNİZ");

        btn_cikis.setText("ÇIKIŞ");
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("HOŞ GELDİNİZ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txb_password, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txb_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btn_giris)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cikis))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combopersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combopersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txb_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(txb_password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_giris)
                    .addComponent(btn_cikis))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combopersonelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combopersonelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combopersonelActionPerformed

    private void btn_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisActionPerformed
        // TODO add your handling code here:
       // int admin=combopersonel(1);
        int ogretmen=combopersonel.getSelectedIndex();
        int ogrenci=combopersonel.getSelectedIndex();
        if(combopersonel.getSelectedItem()=="ADMIN")
        {
           String sql="select * from admintablo where admin_ad=? and admin_password=?";
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
              try (Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.")) {
                  PreparedStatement p=con.prepareStatement(sql);
                  p.setString(1,txb_ad.getText());
                  p.setString(2, txb_password.getText());
                  ResultSet rs=p.executeQuery();
                  if(rs.next())
                  {
                     setVisible(false);
                        Admin object=new Admin();
                    object.setVisible(true);
                  }
                  else{
                      JOptionPane.showMessageDialog(null,"kullanıcı adı şifre geçersiz","başarılı değil",JOptionPane.ERROR_MESSAGE);
                     
                      
                  } }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
        else if(combopersonel.getSelectedItem()=="OGRETMEN")
         {
         String sql="select * from ogretmen_tablo where ogretmen_adsoyad=? and ogretmen_password=?";
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
              try (Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.")) {
                  PreparedStatement p=con.prepareStatement(sql);
                  p.setString(1,txb_ad.getText());
                  p.setString(2, txb_password.getText());
                  ResultSet rs=p.executeQuery();
                  if(rs.next())
                  {  String ogr=txb_ad.getText();
                     setVisible(false);
                       ogretmen object= new ogretmen(ogr);
                    object.setVisible(true);
                   
                  }
                  else{ 
                      JOptionPane.showMessageDialog(null,"kullanıcı adı şifre geçersiz","başarılı değil",JOptionPane.ERROR_MESSAGE);
                     
                  } }
             
             
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         
         }
        else if(combopersonel.getSelectedItem()=="OGRENCI")
         {
             String sql="select * from ogrenci_tablo where ogrenci_adsoyad=? and ogrenci_password=?";
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
              try (Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.")) {
                  PreparedStatement p=con.prepareStatement(sql);
                  p.setString(1,txb_ad.getText());
                  p.setString(2, txb_password.getText());
                  ResultSet rs=p.executeQuery();
                  if(rs.next())
                  {
                     setVisible(false);
                        Ogrenci object=new Ogrenci();
                    object.setVisible(true);
                  }
                  else{
                      JOptionPane.showMessageDialog(null,"kullanıcı adı şifre geçersiz","başarılı değil",JOptionPane.ERROR_MESSAGE);
                      
                  } }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         }
    
    }//GEN-LAST:event_btn_girisActionPerformed

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btn_cikisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaSayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton btn_giris;
    private javax.swing.JComboBox<String> combopersonel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txb_ad;
    private javax.swing.JPasswordField txb_password;
    // End of variables declaration//GEN-END:variables
}
