
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ogretmen extends javax.swing.JFrame {

    /**
     * Creates new form ogretmen
     */
    public ogretmen() {
        initComponents();
        dersGetir();
        jPanel3.setEnabled(false); 
       jButton3.setEnabled(false);
     
    }

    ogretmen(String ogr) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        lbl_ogr.setText(ogr);
        dersGetir();
       jPanel3.setEnabled(false);
         jButton3.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_soru = new javax.swing.JTextArea();
        combo_ders = new javax.swing.JComboBox<>();
        combo_seviye = new javax.swing.JComboBox<>();
        btn_guncelleme = new javax.swing.JButton();
        btn_silme = new javax.swing.JButton();
        btn_listele = new javax.swing.JButton();
        btn_ekleme = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbl_ogr = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txt_hata = new javax.swing.JTextField();
        txt_ogretmen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SORU EKLEME İŞLEMLERİ");

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SORUYU GİRİNİZ");

        text_soru.setColumns(20);
        text_soru.setRows(5);
        jScrollPane1.setViewportView(text_soru);

        combo_seviye.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BASIT", "ORTA", "ZOR" }));
        combo_seviye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_seviyeActionPerformed(evt);
            }
        });

        btn_guncelleme.setText("GÜNCELLE");
        btn_guncelleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncellemeActionPerformed(evt);
            }
        });

        btn_silme.setText("SİL");
        btn_silme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silmeActionPerformed(evt);
            }
        });

        btn_listele.setText("LİSTELE");
        btn_listele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listeleActionPerformed(evt);
            }
        });

        btn_ekleme.setText("EKLE");
        btn_ekleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eklemeActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "SORU", "SEVİYESİ", "OGRETMEN", "DERSİ"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DERS SEÇ");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SEVİYE SEÇ");

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GERİYE GİT");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("uyariya git");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "HATALI SORU", "ÖĞRETMEN"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("hata");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ogretmen");

        jButton3.setText("uyar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_hata)
                            .addComponent(txt_ogretmen, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_hata, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ogretmen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(combo_seviye, 0, 215, Short.MAX_VALUE)
                                    .addComponent(combo_ders, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(17, 17, 17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_ogr, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_ekleme, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_guncelleme)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_silme, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_listele)
                                .addGap(106, 106, 106)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_ogr, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(combo_ders, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(combo_seviye, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ekleme)
                            .addComponent(btn_guncelleme)
                            .addComponent(btn_silme)
                            .addComponent(btn_listele)
                            .addComponent(jButton2))
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_silmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silmeActionPerformed
      DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int indix=jTable1.getSelectedRow();
        int id=Integer.parseInt(model.getValueAt(indix, 0).toString());
         try{ 
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.");
       
                
            PreparedStatement pr;
         
            pr =con.prepareStatement("delete from soru_tablo where id_soru=?");
             
            pr.setInt(1, id);
      
         pr.executeUpdate();
         JOptionPane.showMessageDialog(null, "BAŞARILI");
        
        }
        catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_silmeActionPerformed

    private void btn_eklemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eklemeActionPerformed
        try{ 
             Class.forName("com.mysql.jdbc.Driver");
              Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.");
         String insert="INSERT INTO soru_tablo(soru,seviye,ogretmen,id_ders) values(?,?,?,(select id_ders from ders_tablo where ders = ?))";
        PreparedStatement pst=con.prepareStatement(insert);
         pst.setString(4,combo_ders.getSelectedItem().toString());
         pst.setString(1,text_soru.getText());
         pst.setString(2,combo_seviye.getSelectedItem().toString());
         pst.setString(3,lbl_ogr.getText());
         pst.executeUpdate();
         JOptionPane.showMessageDialog(null, "EKLEME BAŞARILI");
       
        }
        catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_eklemeActionPerformed

    private void combo_seviyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_seviyeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_seviyeActionPerformed

    private void btn_listeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listeleActionPerformed
     
        try{
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.");
           
            PreparedStatement pst=con.prepareStatement("SELECT so.id_soru,so.soru,so.seviye,so.ogretmen,de.ders FROM soru_tablo so,ders_tablo de where so.id_ders=de.id_ders");
           ResultSet rs= pst.executeQuery();
           
           
            DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs.next())
            {
                
             Object o[]={rs.getInt("id_soru"),rs.getString("soru"),rs.getString("seviye"),rs.getString("ogretmen"),rs.getString("ders")};
             df.addRow(o);
            }
       }catch(Exception e)
       {
             JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_btn_listeleActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int selectedRowIndex=jTable1.getSelectedRow();
        text_soru.setText(model.getValueAt(selectedRowIndex,1).toString());
        combo_seviye.setSelectedItem(model.getValueAt(selectedRowIndex,2).toString());
        combo_ders.setSelectedItem(model.getValueAt(selectedRowIndex,3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_guncellemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncellemeActionPerformed
       
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int indix=jTable1.getSelectedRow();
        int id=Integer.parseInt(model.getValueAt(indix, 0).toString());
         try{ 
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.");
        
            PreparedStatement pr;
         
         
            pr =con.prepareStatement("update soru_tablo set soru='"+text_soru.getText()+"',seviye='"+combo_seviye.getSelectedItem()+"',ogretmen='"+lbl_ogr.getText()+"',id_ders=(select id_ders from ders_tablo where ders ='" +combo_ders.getSelectedItem().toString()+"') where id_soru=?  ");
           
            pr.setInt(1, id);
      
         pr.executeUpdate();
         JOptionPane.showMessageDialog(null, "BAŞARILI");
        
        }
        catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_guncellemeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          setVisible(false);
             AnaSayfa object=new AnaSayfa();
             object.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         jPanel3.setEnabled(true);
         try{
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.");
           
            PreparedStatement pst=con.prepareStatement("SELECT * from ogretmen_uyari_tablo where uyari_ogretmen='"+lbl_ogr.getText()+"'");
           ResultSet rs= pst.executeQuery();
           
           
            DefaultTableModel df=(DefaultTableModel)jTable2.getModel();
            df.setRowCount(0);
            while(rs.next())
            {
                
             Object o[]={rs.getInt("id_u"),rs.getString("uyari_soru"),rs.getString("uyari_ogretmen")};
             df.addRow(o);
               jButton3.setEnabled(true);
            }
            
           
       }catch(Exception e)
       {
             JOptionPane.showMessageDialog(null, e);
       }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        int selectedRowIndex=jTable2.getSelectedRow();
        txt_hata.setText(model.getValueAt(selectedRowIndex,1).toString());
        txt_ogretmen.setText(model.getValueAt(selectedRowIndex,2).toString());

    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.");
            String insert="INSERT INTO hatali_soru_tablo(yanlislar,ogretmen) values('"+txt_hata.getText()+"','"+txt_ogretmen.getText()+"')";
            PreparedStatement pst=con.prepareStatement(insert);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "BAŞARILI");
             setVisible(false);
             Duzelt object=new Duzelt();
             object.setVisible(true);
            
         //jButton3.setEnabled(true);
        }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        sil();
        yenile();
    }//GEN-LAST:event_jButton3ActionPerformed
private void dersGetir()
{
    String getir="select * from ders_tablo ";
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.");
        PreparedStatement p=con.prepareStatement(getir);
         ResultSet rs= p.executeQuery();
         while(rs.next())
         {
             combo_ders.addItem(rs.getString("ders"));
             
         }
    }
    catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null, ex);
        }
}
private void sil()
{
 DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        int indix=jTable2.getSelectedRow();
        int id=Integer.parseInt(model.getValueAt(indix, 0).toString());
         try{ 
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.");
       
                
            PreparedStatement pr;
         
            pr =con.prepareStatement("delete from ogretmen_uyari_tablo where uyari_soru='"+txt_hata.getText()+"'");
             
          //  pr.setInt(1, id);
      
         pr.executeUpdate();
         JOptionPane.showMessageDialog(null, "BAŞARILI");
        
        }
        catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null, ex);
        }
}
private void yenile()
{
try{
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.");
           
            PreparedStatement pst=con.prepareStatement("SELECT * from ogretmen_uyari_tablo");
           ResultSet rs= pst.executeQuery();
           
           
            DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs.next())
            {
                
             Object o[]={rs.getInt("id_u"),rs.getString("uyari_soru"),rs.getString("uyari_ogretmen")};
             df.addRow(o);
            }
            
       }catch(Exception e)
       {
             JOptionPane.showMessageDialog(null, e);
       }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ogretmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ogretmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ogretmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ogretmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ogretmen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ekleme;
    private javax.swing.JButton btn_guncelleme;
    private javax.swing.JButton btn_listele;
    private javax.swing.JButton btn_silme;
    private javax.swing.JComboBox<String> combo_ders;
    private javax.swing.JComboBox<String> combo_seviye;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_ogr;
    private javax.swing.JTextArea text_soru;
    private javax.swing.JTextField txt_hata;
    private javax.swing.JTextField txt_ogretmen;
    // End of variables declaration//GEN-END:variables
}
