
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Ogrenci extends javax.swing.JFrame {

    /**
     * Creates new form Ogrenci
     */
    public Ogrenci() {
        initComponents();
        dersGetir();
        listele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btn_getir1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        combo_ders = new javax.swing.JComboBox<>();
        combo_seviye = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_hata = new javax.swing.JButton();
        txt_hata = new javax.swing.JTextField();
        txt_ogretmen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_seviye = new javax.swing.JButton();
        btn_getir2 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        btn_getir1.setText("GETIR");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "SORU", "SEVİYESİ", "ÖĞRETMENİ", "DERSİ"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SORULAR");

        combo_seviye.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BASİT", "ORTA", "ZOR" }));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DERS SEÇ");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SEVİYE SEÇ");

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GERİYE GİT");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_hata.setText("hata uyarısı ver");
        btn_hata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hataActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("hatalı soru");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("öğretmeni");

        btn_seviye.setText("GETIR");
        btn_seviye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seviyeActionPerformed(evt);
            }
        });

        btn_getir2.setText("GETIR");
        btn_getir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_ders, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_seviye, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_getir2)
                            .addComponent(btn_seviye)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(257, 257, 257)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_hata)
                                    .addGap(39, 39, 39)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(126, 126, 126)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txt_hata, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_ogretmen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_ders, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_getir2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_seviye, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_seviye))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hata)
                    .addComponent(txt_hata, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ogretmen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hataActionPerformed
         try{ 
             Class.forName("com.mysql.jdbc.Driver");
              Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.");
         String insert="INSERT INTO uyari_tablo(yanlis_soru,ogretmen) values('"+txt_hata.getText()+"','"+txt_ogretmen.getText()+"')";
        PreparedStatement pst=con.prepareStatement(insert);
       
         
         pst.executeUpdate();
         JOptionPane.showMessageDialog(null, "BAŞARILI");
       
        }
        catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_hataActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int selectedRowIndex=jTable1.getSelectedRow();
        txt_hata.setText(model.getValueAt(selectedRowIndex,1).toString());
        combo_seviye.setSelectedItem(model.getValueAt(selectedRowIndex,2).toString());
        combo_ders.setSelectedItem(model.getValueAt(selectedRowIndex,4).toString());
       txt_ogretmen.setText(model.getValueAt(selectedRowIndex,3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_getir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getir2ActionPerformed
         
        try{
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.");
           String a = combo_ders.getSelectedItem().toString();
            PreparedStatement pst=con.prepareStatement("SELECT so.id_soru,so.soru,so.seviye,so.ogretmen,de.ders FROM soru_tablo so,ders_tablo de where so.id_ders=de.id_ders and de.ders = '"+a+"'");
            ResultSet rs= pst.executeQuery();
           
           
            DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs.next())
            {
                
             Object o[]={rs.getInt("id_soru"),rs.getString("soru"),rs.getString("seviye"),rs.getString("ogretmen"),rs.getString("ders")};
             df.addRow(o);
            }
       }catch(Exception e)
       {
             JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_btn_getir2ActionPerformed

    private void btn_seviyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seviyeActionPerformed
          
        try{
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.");
           String a = combo_seviye.getSelectedItem().toString();
            PreparedStatement pst=con.prepareStatement("SELECT so.id_soru,so.soru,so.seviye,so.ogretmen,de.ders FROM soru_tablo so,ders_tablo de where so.id_ders=de.id_ders and so.seviye = '"+a+"'");
            ResultSet rs= pst.executeQuery();
           
           
            DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs.next())
            {
                
             Object o[]={rs.getInt("id_soru"),rs.getString("soru"),rs.getString("seviye"),rs.getString("ogretmen"),rs.getString("ders")};
             df.addRow(o);
            }
       }catch(Exception e)
       {
             JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_btn_seviyeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
             AnaSayfa object=new AnaSayfa();
             object.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
private void dersGetir()
{
    String getir="select * from ders_tablo ";
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.");
        PreparedStatement p=con.prepareStatement(getir);
         ResultSet rs= p.executeQuery();
         while(rs.next())
         {
             combo_ders.addItem(rs.getString("ders"));
             
         }
    }
    catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null, ex);
        }
}
private void listele()
{
 try{
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sorubanka_database?useTimezone=true&serverTimezone=UTC","root","01A06m0550alp.");
           
            PreparedStatement pst=con.prepareStatement("SELECT so.id_soru,so.soru,so.seviye,so.ogretmen,de.ders FROM soru_tablo so,ders_tablo de where so.id_ders=de.id_ders");
           ResultSet rs= pst.executeQuery();
           
           
            DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs.next())
            {
                
             Object o[]={rs.getInt("id_soru"),rs.getString("soru"),rs.getString("seviye"),rs.getString("ogretmen"),rs.getString("ders")};
             df.addRow(o);
            }
       }catch(Exception e)
       {
             JOptionPane.showMessageDialog(null, e);
       }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ogrenci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_getir1;
    private javax.swing.JButton btn_getir2;
    private javax.swing.JButton btn_hata;
    private javax.swing.JButton btn_seviye;
    private javax.swing.JComboBox<String> combo_ders;
    private javax.swing.JComboBox<String> combo_seviye;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_hata;
    private javax.swing.JTextField txt_ogretmen;
    // End of variables declaration//GEN-END:variables
}
